// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oauckvkigfrunfohaqzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdWNrdmtpZ2ZydW5mb2hhcXprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDMwMDIsImV4cCI6MjA2MTQxOTAwMn0.K-hhlb103cSKpWtAtJwxT-y1TxXp1muQwqtbIrqT3EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);